### ISSUE TITLE
CAN U HELP ME uwu

### ISSUE THREAD

**Issue by thanaponglaboratory** [ThanapongYamkamol642115022/devopsLab03#3]
# The main question is #

How can we add the commit message
we can use the command

    git commit -m "some text"

however, we can use git rebase in the interactive mode to rebase or change the commit message of the old code

# What is the short term for interactive mode #

* i
* u
* v

- - - -

can you answer the question?

- [x] yes
- [x] no

![This is an image](https://media.komchadluek.net/uploads/images/md/2022/11/BoLCMeEIkueY7nVefDkV.webp?x-image-process=style/LG)

**Comment by veevism** [comment]
![w644 (1)](https://user-images.githubusercontent.com/65585968/209198344-eb212781-1363-482d-8c75-4b3c58a0f569.jpeg)

Look Good To Me
